Log system refactor
3liz/lizmap-web-client pull request #1822
Opened 2020-09-16 12:47 UTC by alagroy-42

Refactoring and testing the log classes.
- moving lizmapLogItem and lizmapLogConfig to Lizmap\Logger namespace.
- uncontextualizing Jelix from the classes
- Adding Unit tests for lizmapLogItem

2020-09-17 07:56 UTC, laurentj requested changes

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/JelixContext.php
> +    {
I think the real content of this method is missing. there is no result property, no use of jIniModifier etc...

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogItem.class.php
>  class lizmapLogItem
mark  it as deprecated

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogConfig.class.php
> +class lizmapLogConfig
mark it as deprecated. Probably we could remove it completely. We should inspect external modules to see if this class and lizmapLogItem are used directly.

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/lib/Logger/Config.php
> +    public function __construct($readConfigPath, App\AppContextInterface $appContext)
$readConfigPath is a wrong name. It does not content a path, right?

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/lib/Logger/Config.php
> +            $iniFile = $this->appContext->appConfigPath('lizmapLogConfig.ini.php');
I think it is better if we give the ini filename to the constructor, we could test it easily

2020-09-17 07:56 UTC, laurentj commented on lizmap/modules/lizmap/lib/Logger/Item.php
> +    {
what are these data? what data should contain? at least comments are missing. I would prefer some setter methods to set each data, and this method should only save $this->data. And i didn't find a usage of this method in the code. Probably it is not used at all.

2020-09-17 15:18 UTC, alagroy-42 commented
I couldn't find any references to the update/modify/save method in the LWC code, is it present in any module ? If not, should we delete it ?
@mdouchin

2020-09-18 10:57 UTC, rldhont approved these changes

2020-09-29 13:05 UTC, laurentj requested changes

2020-10-08 10:23 UTC, laurentj requested changes

2020-10-08 10:23 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogConfig.class.php
> +        $this->config = new Log\Config($readConfigPath);
app context parameter is missing

2020-10-08 10:23 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogItem.class.php
> +        return $this->properties;
use Item::getSProperties instead

2020-10-08 10:23 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogItem.class.php
>      private static $properties = array(
remove it and use static method of Item

2020-10-08 10:23 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogItem.class.php
>      private static $recordKeys = array(
remove it

2020-10-08 10:23 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapLogItem.class.php
> +        return $this->item->insertLogDetail($data, $profile);
insertLogDetail does not return a value, so no return

2020-10-08 10:23 UTC, laurentj commented on tests/units/classes/Log/ConfigTest.php
>          unset($testLizmapLogConfig);
no need to unset

2020-10-08 10:24 UTC, laurentj commented
Please fix lint issues showed by checks

2020-10-09 13:21 UTC, laurentj approved these changes

2020-10-09 13:21 UTC, laurentj commented on lizmap/modules/lizmap/lib/Logger/Config.php
> +                $logItemList[] = preg_replace('#(^item:)#', '', $section, 1);
Not optimized. Your code search two times in the string. 

Here is a better solution, search and retrieve at the same time:

```
           if (preg_match('/^item:(.*)/', $section, $matches)) {
                  $logItemList[] = $matches[1];
           }
```

2020-10-09 13:21 UTC, laurentj commented on lizmap/modules/lizmap/lib/Logger/Config.php
> +                $logItemList[] = preg_replace('#(^item:)#', '', $section, 1);
I'll fix it

2020-10-09 13:21 UTC, merged