adding form JSON generator
3liz/lizmap-web-client pull request #1842
Opened 2020-09-30 10:18 UTC by alagroy-42

This is the form JSON Generator in `Lizmap\Project\QgisProject`. If you build the app, you will be able to create the JSON and check it. It will be located in `lizmap/modules/lizmap/forms/project.layer.form.json`. However, the edition part will not work because of the namespace changing and I didn't modify qgisForm* classes to work with the JSON, it will be for another PR.

2020-10-01 08:52 UTC, rldhont approved these changes

2020-10-08 16:06 UTC, laurentj requested changes
you must not store generated files into lizmap directories. Store them into the temp directory.

You should also explain what you're changing into commit messages. I'm not sure what you are doing, since there are too much changes.

2020-10-09 09:35 UTC, alagroy-42 commented
About the json files storing location, I did a method to get it in AppContext in next PR, so I'll fix it on #1844 to avoid conflicts. Sorry for that.

2020-10-09 15:37 UTC, laurentj approved these changes
Looks good to me. I will apply request changes

2020-10-09 15:37 UTC, laurentj commented on lizmap/modules/lizmap/lib/Project/QgisProject.php
> +            if (property_exists($edittype->attributes(), 'widgetv2type')) {
an original comment is missing :  `// New QGIS 2.4 edittypes : use widgetv2type property`

2020-10-09 15:49 UTC, laurentj commented
Merged by hand.

2020-10-09 15:49 UTC, closed without merging