[bugfix] defining undefined variables in lizmapWMSRequest
3liz/lizmap-web-client pull request #1943
Opened 2020-11-27 08:57 UTC by alagroy-42

* Ticket : fixes #1924

2020-11-30 08:44 UTC, laurentj reviewed
It seems ok to me, at the syntax level. But @rldhont knows more than me if new values are correct

2020-11-30 16:45 UTC, rldhont requested changes
I think you have to change line 188 and 193

2020-11-30 16:45 UTC, rldhont commented on lizmap/modules/lizmap/classes/lizmapWMSRequest.class.php
> +        $response->data = preg_replace('/xlink\:href=".*"/', 'xlink:href="'.$sUrl.'&amp;"', $response->data);
```suggestion
        $data = $response->data;
        $data = preg_replace('/xlink\:href=".*"/', 'xlink:href="'.$sUrl.'&amp;"', $data);
```
I prefer to work as immutable even if it is not.
And change the line 93

2020-12-01 09:15 UTC, rldhont commented
@alagroy-42 is this fix for release 3.4 or for 3.5 ?

2020-12-01 09:24 UTC, alagroy-42 commented
@rldhont For release 3.4, these variables exist and are not defined in the current version of the release.

2020-12-01 09:38 UTC, Gustry commented
@alagroy-42 We usually do the bugfix on the lowest branch impacted. So you PR must target 3.4 and not master.
The commit will come back later on master.

2020-12-01 09:45 UTC, closed without merging