Custom Wms headers
3liz/lizmap-web-client pull request #2000
Opened 2020-12-17 16:29 UTC by laurentj

We could need to add custom headers with WMS requests (for metrics, monitoring or else at the qgis server side)

* Funded by 3liz

2020-12-17 16:41 UTC, nboisteault commented
@laurentj can you give a use case please?

2020-12-17 16:46 UTC, rldhont requested changes

2020-12-17 16:46 UTC, rldhont commented on lizmap/modules/lizmap/classes/lizmapProxy.class.php
> +
Can you merge this part with those lines start at line 144
```php
        $options['headers'] = array_merge(
            self::userHttpHeader(),
            $options['headers']
        );
        if (isset($options['loginFilteredOverride'])) {
            $options['headers']['X-Lizmap-Override-Filter'] = $options['loginFilteredOverride'];
        }
```

2020-12-18 08:13 UTC, rldhont approved these changes

2020-12-18 08:21 UTC, nboisteault approved these changes

2020-12-18 08:24 UTC, merged