Docker: change base image tag
3liz/lizmap-web-client pull request #2229
Opened 2021-04-07 13:20 UTC by dmarteau

## Change base image tag from alpine:3.11 to alpine:3

Strict alpine version is too restrictive: it prevents CI builds to take into accounts custom infrastructure choices. 

## Follow convention for php override config name.

Change the name of the custom lizmap override config file dynamically created at startup from the PHP_INI env variable to follow convention.

2021-04-08 09:03 UTC, laurentj requested changes

2021-04-08 09:03 UTC, laurentj commented on docker/lizmap-entrypoint.sh
> +/etc/php7/php.ini# Set up Configuration
bad copy-paste ?

2021-04-08 11:44 UTC, dmarteau commented on docker/lizmap-entrypoint.sh
> +/etc/php7/php.ini# Set up Configuration
Arf, un doigt qui a ripé sur le clavier....

2021-04-08 11:48 UTC, dmarteau commented on docker/lizmap-entrypoint.sh
> +/etc/php7/php.ini# Set up Configuration
Fix pushed...

2021-04-15 16:55 UTC, laurentj approved these changes

2021-04-15 16:55 UTC, merged