Allow use of JS modules (ES6) with docks
3liz/lizmap-web-client pull request #2322
Opened 2021-06-02 09:35 UTC by nboisteault

* Funded by 3Liz

2021-06-02 09:49 UTC, laurentj requested changes

2021-06-02 09:49 UTC, laurentj commented on lizmap/modules/view/classes/lizmapMapDockItem.class.php
> +    public function __construct($id, $title, $content, $order = 0, $css = '', $js = '', $jsParams = array())
Documentation on parameters are missing. 

We should indicate, at least:
- `$js` is an URL of a JS file
- `$jsParams` is an array containing additional attributes for the `<script>` tags, like `type` if not `text/javascript`, or `defer` etc...

2021-06-02 09:49 UTC, laurentj commented on lizmap/modules/view/classes/lizmapMapDockItem.class.php
> +    public function __construct($id, $title, $content, $order = 0, $css = '', $js = '', $jsParams = array())
- `$css` is an URL of a JS file

2021-06-02 09:49 UTC, laurentj commented on lizmap/responses/myHtmlMapResponse.class.php
> +    protected function outputJsScriptTag($fileUrl, $scriptParams)
I just update Jelix into Lizmap, no need any more to redefine this method.

2021-06-02 09:49 UTC, laurentj commented on CHANGELOG-3.5.md
> +- Allow use of JS modules (ES6) with docks.
", by indicating the `type` attribute of `<script>` to `lizmapMapDockItem`."

2021-06-03 08:59 UTC, nboisteault commented on lizmap/modules/view/classes/lizmapMapDockItem.class.php
>      public $icon = '';
@mdouchin `$icon` and `$menuIconClasses` are not in the constructor. It seems they have been forgotten. Should we add them or remove them as they seem unused till now ?

2021-06-03 09:15 UTC, merged