Fix some log messages about XML loading
3liz/lizmap-web-client pull request #2382
Opened 2021-07-16 15:50 UTC by rldhont

Firstly fix `Object of class LibXMLError could not be converted to string` in OGCRequest.

Secondly add error log messages about QGIS Project XML loading

Then add error log messages about WMS GetCapabilities loading in WMTS classes.

* Funded by CRIGE-PACA

2021-07-19 09:13 UTC, nboisteault approved these changes
@rldhont it looks good to me but we have no project to replicate the issue and test your PR.

2021-07-19 15:01 UTC, mdouchin requested changes
I think we should add a method in a utility class to manage the building of the `$errormsg` to avoid to duplicate four times the code (with small changes). Probably could be a method of `lizmap/modules.lizmap/lib/Request/Proxy.php` or in another more appropriate class.

2021-07-20 08:05 UTC, rldhont commented on lizmap/modules/lizmap/classes/lizmapTiler.class.php
> +            if ($wms_xml === false) {
Ok I'll do

2021-07-20 09:38 UTC, rldhont commented on lizmap/modules/lizmap/classes/lizmapTiler.class.php
> +            if ($wms_xml === false) {
done

2021-07-20 09:38 UTC, rldhont commented
@nboisteault @mdouchin can you re-review the code ?

2021-07-20 09:44 UTC, mdouchin approved these changes
👍 thanks

2021-07-20 12:01 UTC, nboisteault approved these changes
Could you add some unit tests?

2021-07-22 08:44 UTC, laurentj requested changes
These new methods are not related at all to Lizmap, and so should not be into the `lizmap` class. I would prefer to have them in the `tools` class or better, into a new `\Lizmap\App\XmlTools` class (into the lib directory of the lizmap module).

2021-07-22 09:43 UTC, rldhont commented
@laurentj thanks for information

2021-07-22 10:17 UTC, rldhont commented
@laurentj new class `\Lizmap\App\XmlTools` created with tests

@nboisteault  unit tests addded

2021-07-22 10:40 UTC, laurentj requested changes
It's ok to me, except DOC comments. It is important to respect the right syntax, to allow IDE to help on auto-completion and type checks, and so to improve the code quality. It helps also to generate a good API documentation (for the day when we will generate such documentations).

Probably we could improve the return type of `xmlFromString` and `xmlFromFile` by returning only one value (`@return SimpleXmlElement|string`). So, instead to do `if (!$xml)`, we could do `if(is_string($xml))` or `if(!is_object($xml))`.  With this returned value, there is not a unused variable (which exists here in both case, error or not), and it makes the signature of the method more readable.

I let you to decide to do the change or to keep as is, but at least  change the comments :-)

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/XmlTools.php
> + * app context informations inside a Jelix environment.
wrong comment, and wrong copyright year ;-)

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/XmlTools.php
> +     * @param $xml_str a well-formed XML string
`string` is missing. The good syntax is `@param string $xml_str  a well-formed XML string`

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/XmlTools.php
> +     * @return ($xml, $msg) Array containing $xml an object of class SimpleXMLElement with properties
the good syntax here is : 

```
* @return array  Array containing a SimpleXMLElement object with properties containing the data held 
*                                  within the XML document, or false on failure ; and a string containing the error message.
```

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/XmlTools.php
> +     * Interprets an XML file into an object
same issue in `@param` and `@return` syntax. See https://docs.phpdoc.org/latest/guide/guides/types.html

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/App/XmlTools.php
> +     * @return $msg a string containing the error message.
`@return string  the error message.`

2021-07-22 10:40 UTC, laurentj commented on lizmap/modules/lizmap/lib/Request/OGCRequest.php
> +     * @param $xmldata a well-formed XML string
`string` keyword is missing in both `@param`

2021-07-22 11:22 UTC, Gustry commented
> It is important to respect the right syntax, to allow IDE to help on auto-completion and type checks, and so to improve the code quality. It helps also to generate a good API documentation (for the day when we will generate such documentations).

Oh yes, big +1.
Can we revive #1755 in the mid term?

2021-07-22 13:11 UTC, laurentj approved these changes
LGTM. Thank you :-)

2021-07-22 13:12 UTC, rldhont commented
Thanks to all

2021-07-22 13:12 UTC, merged