Replace getData() methods by getter methods
3liz/lizmap-web-client pull request #2398
Opened 2021-07-22 16:55 UTC by laurentj

We have few objects having a `getData($key)` method. It returns a value corresponding to a key.

Having these kind of methods is not good for the code:
* we never known which keys value we can give
* we don't know the type of the return value
* as current `getData()` implementations return null if there is no value for the given key, we don't know if it is because the value does not exist or if it is because the key is invalid.
* we cannot specify the type of the return value in a doc comment for IDE, to help auto-completion and type checks

The result is a code that is not very understandable, not robust, not very maintenable.

These patches propose to implement methods for each "data" we want to get from the object, allowing to have documentation about returned value, allowing to know naturally the available data.

* Funded by 3Liz

2021-07-26 12:13 UTC, rldhont approved these changes

2021-07-26 12:23 UTC, nboisteault reviewed
One comment for the moment but I'll test soon.

2021-07-26 12:23 UTC, nboisteault commented on lizmap/modules/lizmap/lib/Project/Repository.php
> +        if ($strVal === 'true' && $strVal === 't'
@laurentj it is `&&` not `||` ?

2021-07-26 12:25 UTC, rldhont requested changes

2021-07-26 12:25 UTC, rldhont commented on lizmap/modules/lizmap/lib/Project/Repository.php
> +        if ($strVal === 'true' && $strVal === 't'
replaced by `in_array()`

2021-07-26 13:00 UTC, mdouchin requested changes

2021-07-26 16:22 UTC, rldhont approved these changes

2021-07-27 07:21 UTC, rldhont commented
@mdouchin your review is needed

2021-07-27 07:44 UTC, mdouchin approved these changes

2021-07-27 07:48 UTC, merged