[BUGIX] Selection & Export - Use the selectiontoken & POST to QGIS Server
3liz/lizmap-web-client pull request #2608
Opened 2021-11-25 13:49 UTC by mdouchin

- Selection: improve the export tool to allow bigger selections
  - use the selection token instead of a list of feature identifiers
  - internally use POST instead of GET requests to query data from QGIS Server

* Funded by 3liz & Faunalia

2021-11-26 08:40 UTC, nboisteault commented
@mdouchin did you execute Cypress?

2021-11-26 08:43 UTC, mdouchin commented
Nope, will do !

2021-11-26 08:46 UTC, Gustry commented
On QGIS, we can launch some specifics workflow by adding a github label on the PR. Maybe a good idea ?

2021-11-26 09:00 UTC, nboisteault commented
Cypress action can be run manually.

2021-11-26 09:09 UTC, nboisteault commented
![cypress_manual](https://user-images.githubusercontent.com/2145040/143555822-3c1814b9-38f2-4912-90be-d32894ea1424.gif)

2021-11-26 09:36 UTC, Gustry commented
Yes, I know, but it's easy to forget and it requires a few clicks to achieve it (and some knowledge)

Adding a label is easy and quick.

2021-11-26 09:41 UTC, nboisteault commented
Do you have a link to an example in QGIS?

2021-11-26 10:18 UTC, nboisteault commented on lizmap/modules/lizmap/lib/Request/Proxy.php
> +            if (count($explode_url == 2)) {
```
2021-11-26 11:16:25	172.25.0.1	warning	[2]	count(): Parameter must be an array or an object that implements Countable
  /srv/lzm/lizmap/modules/lizmap/lib/Request/Proxy.php	284
 /index.php/lizmap/service/?repository=testsrepository&project=filter_layer_data_by_polygon_for_groups&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.0.0
 array (   'repository' => 'testsrepository',   'project' => 'filter_layer_data_by_polygon_for_groups',   'SERVICE' => 'WFS',   'REQUEST' => 'GetCapabilities',   'VERSION' => '1.0.0',   'module' => 'lizmap',   'action' => 'service:index', )
 ref:http://localhost:8130/index.php/view/map/?repository=testsrepository&project=filter_layer_data_by_polygon_for_groups

	0	count()	/srv/lzm/lizmap/modules/lizmap/lib/Request/Proxy.php : 284
	1	Lizmap\Request\Proxy::curlProxy()	/srv/lzm/lizmap/modules/lizmap/lib/Request/Proxy.php : 438
	2	Lizmap\Request\Proxy::getRemoteData()	/srv/lzm/lizmap/modules/lizmap/lib/Request/OGCRequest.php : 205
	3	Lizmap\Request\OGCRequest->request()	/srv/lzm/lizmap/modules/lizmap/lib/Request/OGCRequest.php : 292
	4	Lizmap\Request\OGCRequest->process_getcapabilities()	/srv/lzm/lizmap/modules/lizmap/lib/Request/WFSRequest.php : 128
	5	Lizmap\Request\WFSRequest->process_getcapabilities()	/srv/lzm/lizmap/modules/lizmap/lib/Request/OGCRequest.php : 149
	6	Lizmap\Request\OGCRequest->process()	/srv/lzm/lizmap/modules/lizmap/controllers/service.classic.php : 370
	7	serviceCtrl->GetCapabilities()	/srv/lzm/lizmap/modules/lizmap/controllers/service.classic.php : 105
	8	serviceCtrl->index()	/srv/lzm/lib/jelix/core/jCoordinator.class.php : 235
	9	jCoordinator->process()	/srv/lzm/lizmap/www/index.php : 23
```

2021-11-26 15:18 UTC, mdouchin commented
@rldhont I corrected the url explode part to be active only if there is no body in the request.

2021-11-26 16:44 UTC, rldhont approved these changes

2021-11-26 16:44 UTC, rldhont commented
@mdouchin thanks ;-)

2021-11-30 14:42 UTC, laurentj requested changes

2021-11-30 14:42 UTC, laurentj commented on lizmap/modules/lizmap/controllers/service.classic.php
> +                            $feature_ids[] = implode(',', array_map(fn ($c) => $data->typename.'.'.$c, $data->ids));
if we want to support PHP < 7.4, we should not use the `fn` keyword and this syntax of "short inline function"

2021-11-30 14:42 UTC, laurentj commented on lizmap/modules/lizmap/lib/Request/WMSRequest.php
> +        // Passer l'option avec le mode post
in english please

2021-11-30 14:42 UTC, laurentj commented on lizmap/modules/lizmap/lib/Request/Proxy.php
> +            if (!empty($options['body'])) {
I would write `else if` here.

Any way, I would not do this change, if we store post fields into `$options['body']`

2021-11-30 14:42 UTC, laurentj commented on lizmap/modules/lizmap/lib/Request/Proxy.php
> +                    $postfields = $explode_url[1];
I would probably fill `$options['body']` with `$explode_url[1]`, and set the content type to `application/x-www-form-urlencoded` into `$options['headers']`, so no change to do below.

2021-11-30 16:38 UTC, mdouchin commented
Thanks @laurentj for the review. I adapted the code.
@nboisteault no time at present to add a Cypress test with big data to check the selection...

2021-11-30 17:34 UTC, mdouchin commented
@nboisteault test data with 1000 points for the test project `selection.qgs` : https://drop.chapril.org/download/436759ebee7992d9/#CULBAOowWh-ST0mZNy6xHA

2021-12-01 10:24 UTC, nboisteault commented
@mdouchin I'd like to reproduce the bug first to validate your fix and make the correct Cypress test. I don't have any bug when exporting thousand points in geojson and GML.

2021-12-02 08:25 UTC, mdouchin commented
Have you tried to select all the features before exporting ?

2021-12-07 08:45 UTC, laurentj approved these changes

2021-12-10 14:23 UTC, nboisteault commented
@mdouchin Maybe 1000 points is not enough. How did you have errors previously?

2021-12-13 14:10 UTC, nboisteault commented
@mdouchin I have the same behavior with or without your patch with 10 000 random points. Could you create a layer illustrating the issue?

2021-12-13 14:16 UTC, merged

2021-12-13 14:18 UTC, nboisteault commented
@mdouchin I merged. We'll add tests one day. Please backport.

2021-12-14 09:37 UTC, nboisteault commented
@mdouchin I have backported to release_3_5. I let you backport to release_3_4.

2021-12-16 09:08 UTC, nboisteault commented
@mdouchin please backport to release_3_4 before we release 3.4.8.

2021-12-17 07:34 UTC, rldhont commented
@mdouchin can you dobthe backport for 3.4.8 ?