Change URL ign basemap
3liz/lizmap-web-client pull request #2619
Opened 2021-11-30 15:30 UTC by drillinP

* Ticket : #2496 
* Tous les fonds de carte IGN proposés via le plugin Lizmap sont utilisables sans clé via les nouvelles URL.
Il y a le nom de couche `GEOGRAPHICALGRIDSYSTEMS.MAPS` correspondant au fond de cartes `ign-can` qui n'existe plus, il faut définir par quoi le remplacer ou bien si on le remplace.
* Ensuite pour le fond `ign-cadastre` on proposait `CADASTRALPARCELS.PARCELLAIRE_EXPRESS` avec la clé gratuite et `CADASTRALPARCELS.PARCELS` avec une clé non gratuite or maintenant les 2 sont gratuits. Lequel propose-t-on ? ou alors on propose-t-on au utilisateur de choisir ?

2021-12-01 13:56 UTC, drillinP commented
La différence entre les couches `CADASTRALPARCELS.PARCELLAIRE_EXPRESS` et `CADASTRALPARCELS.PARCELS` sont : 
* Pour la première couche un affichage selon le niveau de zoom

![cadastre_express1](https://user-images.githubusercontent.com/16720972/144246633-f9b9ac22-a4e4-40a7-9f83-2202ce96316f.png)

![cadastre_express2](https://user-images.githubusercontent.com/16720972/144246640-ca091225-f210-4b39-a5ff-73b8bc1fff92.png)

* Pour la deuxième couche un affichage détaillé des parcelles: 

![cadastre1](https://user-images.githubusercontent.com/16720972/144246760-297249e4-2481-47a2-abcb-8ec65e7a21d4.png)

2021-12-02 17:25 UTC, drillinP commented
Après discussion on garde le scan 25 (la couche `GEOGRAPHICALGRIDSYSTEMS.MAPS`) accessible via une clé et pour la partie cadastre on utilise la couche `CADASTRALPARCELS.PARCELLAIRE_EXPRESS`.

2021-12-03 08:59 UTC, rldhont requested changes

2021-12-03 08:59 UTC, rldhont commented on lizmap/www/assets/js/map.js
> +
Remove

2021-12-03 08:59 UTC, rldhont commented on lizmap/www/assets/js/map.js
> +            // layer: isFreeIgnKey ? "CADASTRALPARCELS.PARCELLAIRE_EXPRESS" : "CADASTRALPARCELS.PARCELS",
Remove

2021-12-03 08:59 UTC, rldhont commented on lizmap/www/assets/js/map.js
> +            // style: isFreeIgnKey ? "PCI vecteur" : "normal",
Remove

2021-12-03 11:08 UTC, nboisteault commented
@drillinP pourquoi utilises-tu la clé `cartes` et pas `essentiels` ? C'est en prévision de l'ajout de plus de couches comme indiqué ici : https://geoservices.ign.fr/services-web-experts-cartes ?

2021-12-03 11:23 UTC, nboisteault requested changes

2021-12-03 11:23 UTC, nboisteault commented on lizmap/www/assets/js/map.js
>            var ignKey = evt.config.options.ignKey;
vscode me dit ici : `'ignKey' is declared but its value is never read.ts(6133)`

Je vais ajouter un projet QGIS pour tester manuellement les fonds de carte. STP trouve un moyen d'avoir une clé pour tester que le scan25 fonctionne.

2021-12-03 12:32 UTC, drillinP commented
> @drillinP pourquoi utilises-tu la clé `cartes` et pas `essentiels` ? C'est en prévision de l'ajout de plus de couches comme indiqué ici : https://geoservices.ign.fr/services-web-experts-cartes ?

Je me suis basé sur le services `experts` donc oui les clés que j'utilise sont `cartes`, `ortho` et `parcellaire`, et oui je me suis dis que si jamais on viens a changer ou ajouter des fonds se sera surement à partir du services `experts` vu qu'il fourni plus de possibilités que les autres services.

2021-12-03 12:35 UTC, drillinP commented
@nboisteault Après je peux toujours changer pour le service `essentiels` si il faut mais `experts` me paraissais mieux à mettre en place.

2021-12-03 13:43 UTC, nboisteault requested changes
Il reste à faire 

> STP trouve un moyen d'avoir une clé pour tester que le scan25 fonctionne.

2021-12-03 13:46 UTC, nboisteault commented
> @nboisteault Après je peux toujours changer pour le service `essentiels` si il faut mais `experts` me paraissais mieux à mettre en place.

La clé `cartes` me convient, tu peux laisser.

2021-12-03 14:41 UTC, nboisteault requested changes

2021-12-03 14:41 UTC, nboisteault commented on lizmap/www/assets/js/map.js
>            var ignAttribution = '<a href="http://www.ign.fr" target="_blank"><img width="25" src="https://wxs.ign.fr/static/logos/IGN/IGN.gif" title="Institut national de l\'information géographique e
Il faut sortir cette variable du block sinon il n'y aura pas d'attribution s'il n'y a pas de clé de saisie.

2021-12-03 14:57 UTC, nboisteault approved these changes
Thanks @drillinP

2021-12-03 15:46 UTC, merged

2021-12-03 16:25 UTC, nboisteault commented
@drillinP don't forget backports. It seems you'll have to manually merge for release_3_4.