Server metadata - Get more information from Lizmap plugin & display them in the admin panel
3liz/lizmap-web-client pull request #2654
Opened 2021-12-15 10:19 UTC by mdouchin

Test if the Lizmap plugin for QGIS Server is installed. If so, add more information about QGIS Server installation: version, plugins installed:

* in a new submenu of the Administration panel
![2021-12-15_111616_875x560](https://user-images.githubusercontent.com/3492210/146168141-f5d2a2f8-2b4b-44bb-b3b6-7d57642dbd02.png)

* in the JSON returned by the URL `index.php/view/app/metadata`
```json
{
    "info": {
        "version": "3.6.0-pre",
        "date": "2021-06-21"
    },
    "dependencies": {
        "jelix": {
            "minversion": "1.1.6",
            "maxversion": "1.6.*"
        }
    },
    "qgis_server": {
        "test": "OK",
        "mime_type": "text\/xml; charset=utf-8",
        "http_code": 500,
        "response": "<ServerException>Project file error. For OWS services: please provide a SERVICE and a MAP parameter pointing to a valid QGIS project file<\/ServerException>\n",
        "metadata": {
            "version": "3.16.14",
            "name": "Hannover",
            "version_int": 31614
        },
        "support_custom_headers": null,
        "services": [
            "WMS",
            "WFS",
            "WCS",
            "WMTS",
            "ATLAS",
            "CADASTRE",
            "EXPRESSION",
            "LIZMAP"
        ],
        "plugins": {
            "wfsOutputExtension": {
                "version": "1.5.0"
            },
            "cadastre": {
                "version": "master"
            },
            "lizmap": {
                "version": "master"
            },
            "atlasprint": {
                "version": "3.0.0"
            }
        }
    }
}
```

2021-12-15 10:27 UTC, Gustry approved these changes
I love it !

2021-12-15 10:35 UTC, laurentj approved these changes
LGTM, thank you :)

2021-12-15 10:53 UTC, Gustry requested changes
I'm checking on the server side 😊

2021-12-20 12:52 UTC, Gustry approved these changes
Ok for me.
The server side is ready and documentation https://docs.lizmap.com/3.5/en/install/pre_requirements.html#lizmap-qgis-server-plugin how to enable this new setting.

2021-12-20 12:52 UTC, Gustry commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +server.information.qgis.error.fetching.information.detail=Either the version of the installed QGIS Server is under 3.16, or the Lizmap plugin is not detected in your server, or is installed with a ve
```suggestion
server.information.qgis.error.fetching.information.detail=Either the version of the installed QGIS Server is under 3.10, or the Lizmap plugin is not detected in your server, or is installed with a version under 3.7.0. Please upgrade QGIS Server to minimum 3.10 and install or upgrade the Lizmap plugin to minimum 3.7.0 by reading the documentation about the environment variable https://docs.lizmap.com/3.5/en/install/pre_requirements.html#lizmap-server-plugin
```

2021-12-21 13:43 UTC, merged