UX - Review the error message about the HTTP code from QGIS Server
3liz/lizmap-web-client pull request #2785
Opened 2022-02-18 07:52 UTC by Gustry

* Ticket : fix #2755
* Funded by 3Liz

UX - Review the error message about the HTTP code from QGIS Server

Before, we could have a 200 HTTP from QGIS Server, according to screenshots in #2755 which is misleading for users.

2022-03-07 14:48 UTC, rldhont approved these changes
LGTM

2022-03-07 16:06 UTC, nboisteault approved these changes

2022-03-08 12:12 UTC, laurentj requested changes

2022-03-08 12:12 UTC, laurentj commented on lizmap/modules/admin/templates/server_information.tpl
> +            <i>{@server.information.qgis.error.fetching.information.detail.NO_ACCESS@}</i><br>
`@admin.server`, not `@server`

2022-03-09 09:21 UTC, merged