Revert old cache rules
3liz/lizmap-web-client pull request #2852
Opened 2022-03-22 09:11 UTC by nboisteault

No more necessary since https://github.com/3liz/lizmap-web-client/pull/2729

2022-03-22 09:16 UTC, nboisteault commented
@laurentj I'm not sure about this change : https://github.com/3liz/lizmap-web-client/pull/2852/files#diff-2507844269c2b3d15c0d54a58d870595caca6fc3bcfad6e5e23e708204ee6833L26
Should it be handled by Lizmap backend or the web server?
With our docker test stack if I remove this line the asset is not cached and there is no etag. Maybe because there is `Content-Type: text/javascript;charset=UTF-8` and not `Content-Type: text/javascript` in header?

2022-04-25 09:14 UTC, laurentj commented
@nboisteault as it is a php script, there is no cache by default, so we should set it. However, one year of cache is too high. So we should not remove it, but change its value.

2022-04-25 09:15 UTC, laurentj requested changes

2022-04-25 09:15 UTC, laurentj commented on lizmap/modules/view/controllers/translate.classic.php
> -        $rep->setExpires('+1 year');
we should not remote it, but set a lower duration

2022-04-25 09:16 UTC, laurentj commented on lizmap/modules/view/controllers/translate.classic.php
> -        $rep->setExpires('+1 year');
1 week is a good duration I think

2022-04-25 09:49 UTC, laurentj commented
I merge the PR, and will fix the cache duration, in order to have this patch in the release of the week

2022-04-25 09:49 UTC, merged