[Feature] Edition: Button to restart drawing geometry
3liz/lizmap-web-client pull request #2930
Opened 2022-04-19 07:05 UTC by rldhont

Provide the capability to update geometry with GPS and form coordinates.

* Funded by 3Liz
* Inspired by SDEE 48

2022-04-21 08:32 UTC, nboisteault commented on lizmap/www/assets/js/edition.js
> +                    console.log('featureadded');
You want to keep `console.log`?

2022-04-21 08:33 UTC, nboisteault approved these changes

2022-04-21 08:33 UTC, nboisteault commented on lizmap/www/assets/js/edition.js
> +                    console.log('featureadded drawWasActivated: '+drawWasActivated);
You want to keep console.log?

2022-04-26 08:23 UTC, mdouchin requested changes
Shouldn't we add a confirm message to be sure the user wants to launch this tool ? If I undestand correctly, this will delete the current drawing without the possibility to go back (or only by canceling the edition, and so loosing all the modified attribute form data

2022-05-30 10:11 UTC, rldhont commented
@mdouchin I have made the requested changes.

2022-05-30 10:24 UTC, mdouchin requested changes

2022-05-30 10:24 UTC, mdouchin commented on lizmap/modules/view/locales/en_US/dictionnary.UTF-8.properties
> +edition.confirm.restart-drawing=Are you sure you want to delete geometry and restart drawing?
```suggestion
edition.confirm.restart-drawing=Are you sure you want to delete the existing geometry and redraw it from scratch ?
```

2022-05-30 10:24 UTC, mdouchin commented on lizmap/modules/view/locales/en_US/edition.UTF-8.properties
> +geomtool.restartdrawing.title=Restart drawing
```suggestion
geomtool.restartdrawing.title=Redraw the geometry
```

2022-05-30 10:38 UTC, rldhont commented
Thanks @mdouchin changes integrated

2022-05-30 11:44 UTC, mdouchin approved these changes

2022-05-30 11:47 UTC, merged