Administration - QGIS project list: add information from qgis-project-validator
3liz/lizmap-web-client pull request #2953
Opened 2022-04-26 10:30 UTC by mdouchin

* Funded by: Valabre (Centre de gravité de la formation des métiers de la Sécurité Civile, de la Recherche, des Nouvelles Technologies et de la Prévention dans le domaine des risques naturels)

2022-04-26 13:13 UTC, laurentj requested changes
- since the beginning, we are using camelCase variable names. We should continue with this coding style. So I recommend to not use `$variable_name_like_this` in PHP, but `$variableNameLikeThis`
- I suggest an other name for `qgisProjectsInspectionDataFolder`: `qgisProjectsPrivateDataFolder`. If we want to reuse later this directory for data other than "inspection"...

2022-04-26 13:13 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapServices.class.php
> +            if (!preg_match('#/$#', $qgisProjectsInspectionDataFolder) && $qgisProjectsInspectionDataFolder !== false) {
It is faster I guess: `$qgisProjectsInspectionDataFolder = rtrim($qgisProjectsInspectionDataFolder, '/').'/';`

2022-04-26 14:36 UTC, mdouchin commented on lizmap/var/config/lizmapConfig.ini.php.dist
> +; if not give, try to use the rootRepositories path
Thanks, modified

2022-04-26 14:45 UTC, Gustry approved these changes
Already approved by giving you a cookie for this work today ;-)

2022-04-27 08:56 UTC, laurentj approved these changes
lgtm

2022-04-27 09:17 UTC, rldhont commented
@mdouchin changelog ?

2022-04-27 09:24 UTC, Gustry commented
> @mdouchin changelog ?

I think it's already done from his previous PR : https://github.com/3liz/lizmap-web-client/blob/master/CHANGELOG-3.6.md#added

2022-04-27 09:29 UTC, rldhont commented
> > @mdouchin changelog ?
> 
> I think it's already done from his previous PR : https://github.com/3liz/lizmap-web-client/blob/master/CHANGELOG-3.6.md#added

OK

2022-04-27 10:45 UTC, mdouchin commented
Changelog for 3.6 improved. I merge !

2022-04-27 10:45 UTC, merged