Layer legend - Use the new option in config to display the legend image at startup
3liz/lizmap-web-client pull request #2994
Opened 2022-05-12 12:09 UTC by mdouchin

Use the new option in Lizmap plugin dedicated to the layer legend image (in the layer tree)

* `auto`: same behaviour as before. The layer legend can be displayed by clicking on the arrow button
* `show`: show the legend image at startup
* `hide`: do not show the legend, nor the arrow to display it (as done before with the `noLegendImage` property)

* Funded by **Conseil Départemental du Gard (France)**

2022-05-12 15:05 UTC, Gustry approved these changes
LGTM

2022-05-13 14:45 UTC, Gustry commented on lizmap/www/assets/js/map.js
> +      lizmap_plugin_version: 30108,
Note for myself, I need to add a new key lizmap plugin version as int ...
In the CFG, it's like : 
```json
    "metadata": {
        "qgis_desktop_version": 31615,
        "lizmap_plugin_version": "3.7.7",
        "lizmap_web_client_target_version": 30500,
        "project_valid": true
    },
```

2022-05-23 09:06 UTC, Gustry requested changes

2022-05-23 09:06 UTC, Gustry commented on lizmap/www/assets/js/map.js
> +      html += ' expanded ';
```suggestion
    // Legend properties
    // Read the plugin metadata to get the legend options
    // depending on the configuration version
    let lizmap_plugin_metadata = getLizmapDesktopPluginMetadata();
    if (lizmap_plugin_metadata.lizmap_web_client_target_version >= 30600) {
      var legendOption = nodeConfig.hide_at_startup;
    } else {
      var legendOption = 'hide_at_startup';
      if (nodeConfig.noLegendImage && nodeConfig.noLegendImage == 'True') {
        legendOption = 'hide_at_startup';
      }
    }

    // Expand layer legend at startup
    if (nodeConfig.type == 'layer' && legendOption == 'expand_at_startup') {
      html += ' expanded ';
```

2022-05-23 09:06 UTC, Gustry commented on lizmap/www/assets/js/map.js
> +    && (legendOption != 'hide')
```suggestion
    && (legendOption != 'hide_at_startup')
```

2022-05-23 09:06 UTC, Gustry commented on lizmap/www/assets/js/map.js
> +        legendOption = 'hide';
```suggestion
      var legendOption = 'hide_at_startup';
      if (nodeConfig.noLegendImage && nodeConfig.noLegendImage == 'True') {
        legendOption = 'disabled';
```

2022-05-23 09:08 UTC, Gustry commented
New CFG in https://github.com/3liz/lizmap-plugin/pull/420 : 

* `legend_image_option` : 
  * `hide_at_startup`
  * `expand_at_startup`
  * `disabled`

Just to be a little bit more explicit, `hide` versus `disabled`.

2022-06-01 17:10 UTC, Gustry commented
Test can be added after #3020 in the `tests/end2end/cypress/integration/legend-ghaction.js` file.

2022-06-03 14:46 UTC, Gustry approved these changes

2022-06-13 09:49 UTC, rldhont approved these changes

2022-06-13 09:50 UTC, merged