Config - Make a single configuration for version using an INI file
3liz/lizmap-web-client pull request #3139
Opened 2022-07-29 15:42 UTC by Gustry

Linked to #2972

2022-07-29 16:07 UTC, laurentj commented
Anyway, you should not use `\Jelix\IniFile\IniModifier` to read an ini file, it takes many resources. Just use `$ini = jIniFile::read($filename); $val = $ini['versions']['qgisMinimumVersionRequired']`

2022-07-29 21:00 UTC, Gustry commented
Thanks, updated.
I was following @mdouchin comment in https://github.com/3liz/lizmap-web-client/pull/3132#issuecomment-1199376866 about the new file. But indeed, it looks ok like this.

2022-08-01 09:15 UTC, mdouchin requested changes
Thanks. Just a small change requested

2022-08-01 09:15 UTC, mdouchin commented on lizmap/app/system/mainconfig.ini.php
> +[minimumRequiredVersion]
Please add a concise comment above with a `;` to explain the purpose of these new variables

2022-08-01 09:26 UTC, merged

2022-08-01 09:34 UTC, Gustry commented
> The backport to `release_3_5` failed:

Manually backported