input type number in edition form when datatype is number
3liz/lizmap-web-client pull request #3280
Opened 2022-10-13 09:37 UTC by nworr

Overload the input_htmlbootstrapFormWidget : outputContol method
Check if datatype is integer and use input type : number
by default, input type is text

browser will perform live validation and add spin button
Ticket : #2992 
 
![input_number](https://user-images.githubusercontent.com/43475951/195559606-d6f9c2fc-ba68-4652-841e-8a839efcfce3.gif)

2022-10-13 09:53 UTC, Gustry commented
Nice addition !
Which option does it support from QGIS UI about this widget ? (min, max, step, suffix ?) I can see "max" from your PR.
Would it close #2992 ?

2022-10-13 09:59 UTC, Gustry commented
A few GH Action did not run, maybe because of the branch ?

2022-10-13 10:25 UTC, laurentj approved these changes
lgtm :-)

2022-10-13 13:13 UTC, nworr commented
@Gustry > currently when these options are set in QGIS UI , min & max  values are used for form validation only, 
suffix and step are ignored

but min/max/step can be used to setup html input form ,I'm working on it (on number only) , see (https://caniuse.com/input-number)

> Currently no mobile browsers and very few desktop browsers support using commas for languages where commas are used as decimal separators.

2022-10-14 07:43 UTC, rldhont requested changes

2022-10-14 07:43 UTC, rldhont commented on lizmap/plugins/formwidget/input_htmlbootstrap/input_htmlbootstrap.formwidget.php
> +        } else {
```suggestion
        if ( $this->ctrl->datatype instanceof jDatatypeDecimal) {
            // Input Number
            // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number
            $attr['type'] = 'number';
            $minValue = $this->ctrl->datatype->getFacet('minValue');
            if ($minValue !== null) {
                $attr['min'] = $minValue;
            }
            $maxValue = $this->ctrl->datatype->getFacet('maxValue');
            if ($maxValue !== null) {
                $attr['max'] = $maxValue;
            }
            // Allow decimal value
            // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number#allowing_decimal_values
            if ( !($this->ctrl->datatype instanceof jDatatypeInteger) ) {
                $attr['step'] = 0.1;
            }
        } else {
```

2022-10-17 08:07 UTC, rldhont requested changes

2022-10-17 08:08 UTC, rldhont commented on lizmap/modules/lizmap/lib/Form/QgisFormControl.php
> +                    }
Documentation about decimal values in input type number https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number#allowing_decimal_values

2022-10-17 08:36 UTC, nworr commented on lizmap/modules/lizmap/lib/Form/QgisFormControl.php
> +                    }
stepvalue 0.1 will forbid user to use lower granularity (0.01) . 
special value `any` can be used

2022-10-17 09:47 UTC, rldhont commented on lizmap/modules/lizmap/lib/Form/QgisFormControl.php
> +                    }
Can we know the field precision ?

2022-10-17 13:15 UTC, nworr commented on lizmap/modules/lizmap/lib/Form/QgisFormControl.php
> +                    }
only in "Range"  type, so i can set a step value according to it (precision = 4 > step = 0.0001) and `any` elsewhere ?

Any reason why Step is handled as int ? https://github.com/3liz/lizmap-web-client/blob/041cdd72bc190be582065ea7cd2501c447d7b580/lizmap/modules/lizmap/lib/Project/QgisProject.php#L2087

2023-01-02 15:21 UTC, rldhont commented
@nworr if the work is ended you can update your branch with master and the PR.

2023-01-18 09:38 UTC, nworr commented
@nboisteault can tou take a look to playwright tests ?

2023-01-31 08:35 UTC, nboisteault commented
We could also use `pattern="[0-9]"` to even go further.

2023-06-15 12:09 UTC, nworr commented
i change end2end tests : 

- playwright test check if `input` element has proper attributes (type=numbrer,  min, max, step)
- cypress test perform form validation tests as if the browser don't support input type number

2023-06-15 13:14 UTC, rldhont approved these changes

2023-06-15 13:15 UTC, rldhont commented
Thanks @nworr you can merge at the end of the tests.

2023-06-15 15:23 UTC, nworr commented
to be more precise :  the 'step' configuration will be verified by browser only, at this time jelix forms doesn't implement step verification

2023-06-16 08:04 UTC, merged