allow space and dot in project filename
3liz/lizmap-web-client pull request #3289
Opened 2022-10-20 09:55 UTC by nworr

project file name can now have space or . in it (test.cats.qgs, "my filename.qgs" 

Ticket : #2353   and #2020

Funded by 3Liz

2022-10-20 11:39 UTC, mdouchin commented
@nworr I just added the tag "Run cypress" to see if it is green

2022-10-27 14:30 UTC, laurentj commented
I don't believe it fixes #2020. Some unit tests should be added (probably by renaming a test project ?)

2022-11-02 13:30 UTC, rldhont requested changes
Adding tests

2022-11-03 16:23 UTC, nworr commented
new test added : 
 - project file with space / dot : [85d9a00](https://github.com/3liz/lizmap-web-client/pull/3289/commits/85d9a0031ac1b8e75e8d9e86f17b9d03e5ab0242)
 - cypress test launch projet and check if layer exists  [9ee5777](https://github.com/3liz/lizmap-web-client/pull/3289/commits/9ee577732193a88c665306094bbc9e910e3a3065)

2022-11-04 10:58 UTC, nworr commented
working on a  playwright test instead of cypress

2022-11-09 09:34 UTC, Gustry approved these changes
LGTM

2022-11-09 09:34 UTC, Gustry commented on tests/end2end/cypress/integration/projects_filename_dot_space-ghaction.js
> +    it('projet with dot or spacr can be loaded', () => {
```suggestion
    it('projet with dot or space can be loaded', () => {
```

2022-11-10 08:56 UTC, rldhont approved these changes

2022-11-10 09:56 UTC, laurentj approved these changes

2022-11-10 09:57 UTC, merged