[docker] wait after the Postgresql server before installing lizmap
3liz/lizmap-web-client pull request #3290
Opened 2022-10-20 14:12 UTC by laurentj

During the startup, especially for the first start when the installer is launched for the first time and SQL table should be created, the container should wait after the Postgresql server, before launching the installer.

If the profiles.ini.php is configured to use a Postgresql database, the container tries to connect to the database 10 times before returning an error.

Funded by 3Liz

2022-10-20 15:00 UTC, laurentj commented on docker/update-config.php
> +        sleep(2);
why not, I will add another environment variable

2022-10-22 16:39 UTC, mdouchin requested changes

2022-10-22 16:39 UTC, mdouchin commented on docker/README.md
> +   two retries of connecting to Postgresql during the startup. Default is 2 seconds.
```suggestion
- `LIZMAP_DATABASE_CHECK_RETRIES`: Number of retries to connect to the PostgreSQL database
   during the startup of the container (default is 10). Used only if Lizmap is configured to
   use a PostgreSQL database (see [profiles.ini.php](https://docs.lizmap.com/3.5/en/install/linux.html#postgresql)).
   The startup script waits for 2 seconds before retries (see `LIZMAP_DATABASE_CHECK_WAIT_BEFORE_RETRY`).
- `LIZMAP_DATABASE_CHECK_WAIT_BEFORE_RETRY`: the amount of time in seconds, between
   two retries of connecting to the PostgreSQL database during the startup. Default is 2 seconds.
```

2022-10-28 10:10 UTC, Gustry commented
Forward port labels for 3.6 and master ? Or did you plan to do it manually ?

2022-11-07 13:31 UTC, merged