Embed layer test
3liz/lizmap-web-client pull request #3334
Opened 2022-11-17 10:36 UTC by nworr

Add new project with embed layer
and playwright test

Ticket : #3326  

Funded by 3liz

2022-12-01 10:26 UTC, nboisteault requested changes

2022-12-01 10:26 UTC, nboisteault commented on tests/end2end/cypress/integration/projects_embed_layer-ghaction.js
> +// projects_filename.js created with Cypress
Please just put a test for playwright.

2022-12-01 10:26 UTC, nboisteault commented on tests/end2end/playwright/startup.spec.js
> +    const url_dots = '/index.php/view/map/?repository=testsrepository&project=embed_layer';
Why `url_dots` variable name?

2022-12-01 10:26 UTC, nboisteault commented on tests/end2end/playwright/startup.spec.js
> +    await page.$eval("#map, #map *", el => el.style.visibility = 'visible');
Why hiding other elements?

2023-09-06 04:20 UTC, closed without merging

2023-09-07 08:55 UTC, nboisteault commented
@nworr should it be reopened?

2023-09-07 12:34 UTC, nworr commented
IMHO, the project file is way too simple to ensure embed layers actually works,  there may problematic use case that need to be checked ( user-filtered layers, mutiple projections, ...).