add lizmap version to proxy request
3liz/lizmap-web-client pull request #3373
Opened 2022-12-16 11:56 UTC by nworr

Proxy Request currently use "Lizmap" as user-agent in request header, that can be usefull for OGC service

the PR add the current lizmap Version

Ticket : #2044

Funded by 3liz

2023-01-02 15:18 UTC, rldhont commented
@nworr I think you have to rebase your branch to avoid conflict with phptan tests fixes.

2023-01-06 13:35 UTC, laurentj requested changes

2023-01-06 13:35 UTC, laurentj commented on lizmap/modules/lizmap/classes/lizmapServices.class.php
> +        $appInfos = \Jelix\Core\Infos\AppInfos::load();
Retrieve the userAgent in an `else` statement of the statement ` if (isset($readConfigPath['services']['userAgent'])) {`. 
`AppInfos` loads xml file, and so it takes some resources. We could avoid to load this file if we don't need it.

2023-01-25 12:39 UTC, rldhont commented
@laurentj requested  changes done.

2023-01-25 12:40 UTC, rldhont approved these changes

2023-02-13 16:31 UTC, laurentj requested changes

2023-08-21 07:06 UTC, rldhont commented
@nworr it is ready for merging?

2023-08-21 16:58 UTC, merged