Admin: Enhancing user experience in repository creation
3liz/lizmap-web-client pull request #3416
Opened 2023-01-18 15:46 UTC by rldhont

In the admin lizmap repository creation page, the form has been enhanced with:

* help strings
* new organization fo fields with path as first, label as second and id as third
* autocompletion for label and id based on selected path

![lizmap-update-config-section-form](https://user-images.githubusercontent.com/1575538/213218580-54bd4e73-8cab-4105-864e-6d7aa5e53dac.png)

Funded by 3liz https://3liz.com

2023-01-18 16:04 UTC, mdouchin requested changes
Some propositions :D

2023-01-18 16:04 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +form.admin_section.repository.help=Repository id for machine, any characters between a-z and 0-9
```suggestion
form.admin_section.repository.help=Repository unique identifier, must only contain characters between a-z and 0-9 (no space, no special character)
```

2023-01-18 16:04 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +form.admin_section.repository.label.help=Repository title for human, it will display in the interface
```suggestion
form.admin_section.repository.label.help=Repository label, which will be displayed in the interface
```

2023-01-18 16:04 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +form.admin_section.repository.path.help=The directory in which QGIS Projects and lizmap config will be displayed
```suggestion
form.admin_section.repository.path.help=The directory in which QGIS Projects and Lizmap configuration file must be added
```

2023-01-18 16:04 UTC, mdouchin commented on lizmap/www/assets/js/admin/config_section.js
> +    console.log(repIdInput.hasAttribute('readonly'));
Remove `console.log` ?

2023-01-18 16:33 UTC, rldhont commented
Thnaks @mdouchin all has been resolved

2023-01-19 10:37 UTC, Gustry approved these changes

2023-01-19 10:37 UTC, Gustry commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +form.admin_section.repository.help=Repository unique identifier, must only contain characters between a-z and 0-9 (no space, no special character)
```suggestion
form.admin_section.repository.help=Repository unique identifier, must only contain characters between a-z and 0-9 (no space, no special character). This identifier can not be edited later.
```

2023-01-19 10:37 UTC, Gustry commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +form.admin_section.repository.path.help=The directory in which QGIS Projects and Lizmap configuration file must be added
```suggestion
form.admin_section.repository.path.help=The directory in which QGIS projects and Lizmap configuration file must be stored.
```

2023-01-19 11:05 UTC, rldhont commented
@mdouchin locale has been updated

2023-01-20 10:10 UTC, nboisteault approved these changes

2023-01-20 14:13 UTC, mdouchin approved these changes

2023-01-20 14:14 UTC, merged