UI admin: Change anchor color for selected line in projects table
3liz/lizmap-web-client pull request #3447
Opened 2023-01-31 13:33 UTC by rldhont

The anchor color in the projects table is the same as the background selected line.

Old UI

![css-admin-table-project-anchor-old](https://user-images.githubusercontent.com/1575538/215774246-c4ecf231-e4d6-4086-bda0-54c0bd08b6a5.png)

New UI

![css-admin-table-project-anchor-new](https://user-images.githubusercontent.com/1575538/215774287-3e02ce20-c3ad-401b-bea6-11014a5ece21.png)

Funded by 3liz

2023-01-31 13:59 UTC, mdouchin requested changes
Thanks for this proposal. Minor improvements

2023-01-31 13:59 UTC, mdouchin commented on lizmap/www/assets/css/admin.css
> +  color: #005580;
I would have kept the white + underline the text
```suggestion
  color: white;
  text-decoration: underline dotted;
```

2023-01-31 14:06 UTC, rldhont commented
Thanks @mdouchin I have updated the description. I will rebase before merge.

2023-01-31 16:10 UTC, nboisteault approved these changes

2023-02-01 08:58 UTC, mdouchin approved these changes

2023-02-01 08:58 UTC, merged