UX - Add explanations about colours in the table
3liz/lizmap-web-client pull request #3461
Opened 2023-02-03 16:45 UTC by Gustry

WIP about colours explanation

![image](https://user-images.githubusercontent.com/1609292/216659242-eabee192-d677-4b74-8924-806d533abb4b.png)

* [ ] Add a span with colour for visual aspect
* [ ] Make strings translatable
* [ ] Rephrase

2023-02-06 13:35 UTC, Gustry commented
![image](https://user-images.githubusercontent.com/1609292/216982996-e8b0ff6c-1577-4033-8fa4-334825c2c45f.png)


All rules added, with a blocking rules versus not blocking.

@nworr Do you think you can contribute by adding a plugin template to format versions ? https://docs.jelix.org/fr/manuel/plugins/tpl Similar to what you did in #3449 It would be nice if you can contribute on this PR ? 😊

Side request as well @nworr Is-it possible to add `<strong>%s</strong>` in a `.properties` files ? I prefer the rendering of my first screenshot with these dynamic values in bold.

2023-02-06 16:35 UTC, nworr commented
@Gustry i add modifier : `qgis_majmin_human_version` , but for the locale you may use the function `jtpl_modifier_common_qgis_majmin_human_version`

You can use html tags in the locale, but not sure it's the best way

2023-02-07 15:21 UTC, Gustry commented
Ready for review : 

![image](https://user-images.githubusercontent.com/1609292/217286233-61404dbb-86dd-46f2-9533-bef7078fffcb.png)

@mdouchin Can you check the strings ?

Maybe we can come back if we really want to add the last bullet point about the colors ?

2023-02-08 09:28 UTC, Gustry commented on lizmap/modules/admin/templates/project_list_zone.tpl
> +    <b>{@admin.project.rules.list.introduction@}</b>
```suggestion
    <strong>{@admin.project.rules.list.introduction@}</strong>
```

2023-02-08 11:11 UTC, Gustry commented on lizmap/modules/admin/zones/project_list.zone.php
> +            $serverVersions['qgis_server_version_humanreadable'] = $this->qgisMajMinHumanVersion($qgisServerVersionInt);
```suggestion
            $serverVersions['qgis_server_version_human_readable'] = $this->qgisMajMinHumanVersion($qgisServerVersionInt);
```

2023-02-08 11:11 UTC, Gustry commented on lizmap/modules/admin/templates/project_list_zone.tpl
> +        {jlocale "admin.project.rules.list.description.html", array($lizmapVersion, ($serverVersions['qgis_server_version_humanreadable']))}
```suggestion
        {jlocale "admin.project.rules.list.description.html", array($lizmapVersion, ($serverVersions['qgis_server_version_human_readable']))}
```

2023-02-09 09:30 UTC, mdouchin requested changes
LGTM, some minor changes requested

2023-02-09 09:30 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +server.information.error=Before checking your projects, you must check your QGIS server settings in the "server information" panel. The configuration is currently not correct about QGIS Server.
```suggestion
server.information.error=Before checking your projects, you must check your QGIS server settings in the "Server information" menu. The configuration of QGIS Server is currently not correct.
```

2023-02-09 09:30 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +project.rules.list.warning.memory.html=Light yellow if the project takes more than <strong>%s</strong> Mo to load.
```suggestion
project.rules.list.warning.memory.html=Light yellow if the project takes more than <strong>%s</strong> Mo of the server memory to load.
```

2023-02-09 09:30 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +project.rules.list.error.memory.html=Light coral if the project takes more than <strong>%s</strong> Mo to load.
```suggestion
project.rules.list.error.memory.html=Light coral if the project takes more than <strong>%s</strong> Mo of the server memory to load.
```

2023-02-09 09:30 UTC, mdouchin commented on lizmap/modules/admin/locales/en_US/admin.UTF-8.properties
> +project.rules.list.custom.projection=Light coral if the project is using a <strong>user defined</strong> projection.
```suggestion
project.rules.list.custom.projection=Light coral if the project is using a <strong>user-defined</strong> projection.
```

2023-02-09 09:45 UTC, merged