use binaryResponse instead of deprecated streamedResponse
3liz/lizmap-web-client pull request #3476
Opened 2023-02-13 16:26 UTC by nworr

quickfix #3462 
 
Funded by 3liz

2023-02-13 16:55 UTC, rldhont commented
waiting for https://github.com/jelix/jelix/pull/393

2023-02-13 16:57 UTC, rldhont requested changes

2023-02-13 16:57 UTC, rldhont commented on lizmap/modules/filter/controllers/service.classic.php
>              $response = $this->getResponse('streamed');
```suggestion
            $response = $this->getResponse('binary');
```

2023-02-14 14:14 UTC, rldhont commented
Unrelated tests failed

2023-02-14 14:14 UTC, rldhont approved these changes

2023-02-14 15:24 UTC, laurentj approved these changes

2023-02-14 15:27 UTC, merged