Check QGIS desktop plugin version for edited QGS file
3liz/lizmap-web-client pull request #4269
Opened 2024-03-05 14:06 UTC by Gustry

* For **edited** QGS file recently, we check if the plugin was up to date (less than a 2 months for instance)

This is to avoid a situation I got recently with QGIS Desktop 3.34 but a plugin from end of 2022.

To be discussed and polished

Funded by 3Liz

2024-03-06 15:54 UTC, mdouchin requested changes

2024-03-06 15:54 UTC, mdouchin commented on lizmap/modules/lizmap/lib/Project/ProjectMetadata.php
> +        $projectDate = strtotime($this->getLastSaveDateTime());
Perhaps add here a fallback to `getFileTime` if `getLastSaveDateTime` returns no data ?

2024-03-06 15:54 UTC, mdouchin commented on lizmap/modules/lizmap/lib/Project/QgisProject.php
> +    }
This would consume a lot of RAM, we need to check how to solve this. Let-s check other functions in the same file too.

2024-03-07 11:15 UTC, Gustry commented
Ok, thanks for the review.

I will come back very soon with an alternative. I keep this branch as an archive for now.

2024-03-08 08:35 UTC, Gustry commented
After some discussions, reopening this PR.

2024-03-12 16:14 UTC, Gustry commented
Archiving this PR, I made #4287 instead for now.
We can come back later with this PR about a better edited date detection.

2024-03-12 16:14 UTC, closed without merging