[Bugfix] Initialization of group checkboxes based on Lizmap configuration
3liz/lizmap-web-client pull request #4657
Opened 2024-07-26 10:06 UTC by mind84

Groups, at any level, will be initialized according to `Lizmap` plugin configuration.

![image](https://github.com/user-attachments/assets/0c32cbd0-d4ae-428e-add1-dbbeb50b811f)

This topic has generated a few tickets/discussions, and since a lot of work has been done on groups lately, I've tried to pay attention to this to preserve any fixes made thus far (referring to PR https://github.com/3liz/lizmap-web-client/pull/4622 https://github.com/3liz/lizmap-web-client/pull/4618 )

The main reason why I want to propose this fix is ​​that the `Permalink` functionality already supports this type of initialization and I basically couldn't find any valid reason not to support this behavior on clean map initialization.

**TECHNICAL NOTES:**

- As said, all "group checkboxes" fix done so far should be preserved
- These changes affected many test files (`unit` tests and `e2e` tests), which were updated accordingly.
- I had to take into account the `hide checkboxes for groups` option to force the groups to be checked if checkbox is hided, despite the configuration. Since this option is not layer-specific, I had to pass the `option config object` through the `layertree` initialization methods and this also generated a lot of changes in the test files. However, passing `option` object might come in handy if there are new "global" options on the layertree in the future.
- Changes affects only map intialization. User interaction after map init is not changed (e.g. if user turn on al "sub layer", then corresponding parent group will be activated)

Ticket : #3968, #4232

Funded by Faunalia

2024-07-30 10:26 UTC, rldhont requested changes
It is not necessary to pass the entire `Options` object for one variable, and because it is `group` specific the default checked value based on `hideGroupCheckbox` has to be done in the `LayerGroupState` constructor.

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/State.js
> +            this._collection = new LayersAndGroupsCollection(this._initialConfig.layerTree, this._initialConfig.layersOrder, this._initialConfig.options);
```suggestion
            this._collection = new LayersAndGroupsCollection(this._initialConfig.layerTree, this._initialConfig.layersOrder, this._initialConfig.options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +import { OptionsConfig } from '../config/Options.js';
```suggestion
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}       options          - the option instance from lizMap configuration
```suggestion
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +    constructor(type, layerTreeItemCfg, options, parentGroup) {
```suggestion
    constructor(type, layerTreeItemCfg, parentGroup) {
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}       options          - the option instance from lizMap configuration
```suggestion
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        super('layer', layerTreeItemCfg, options, parentMapGroup);
```suggestion
    constructor(layerTreeItemCfg, layersOrder, parentMapGroup) {
        super('layer', layerTreeItemCfg, parentMapGroup);
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}       options          - the option instance from lizMap configuration
```suggestion
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        super(layerTreeItemCfg, layersOrder, options, parentMapGroup)
```suggestion
    constructor(layerTreeItemCfg, layersOrder, parentMapGroup) {
        super(layerTreeItemCfg, layersOrder, parentMapGroup)
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}       options          - the option instance from lizMap configuration
```suggestion
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        super(layerTreeItemCfg, layersOrder, options, parentMapGroup)
```suggestion
    constructor(layerTreeItemCfg, layersOrder, parentMapGroup) {
        super(layerTreeItemCfg, layersOrder, parentMapGroup)
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        this._checked = this._parentGroup == null ? true : (type == 'group' && options.hideGroupCheckbox ? true : this._layerTreeItemCfg.layerConfig.toggled);
```suggestion
        // prop checked is inherithed from Lizmap configuration
        this._checked = this._parentGroup == null ? true : this._layerTreeItemCfg.layerConfig.toggled;
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}       options            - the option instance from lizMap configuration
```suggestion
     * @param {boolean}       hideGroupCheckbox            - the hideGroupCheckbox option instance from lizMap configuration
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        super('group', layerTreeGroupCfg, options, parentMapGroup);
```suggestion
    constructor(layerTreeGroupCfg, layersOrder, hideGroupCheckbox, parentMapGroup) {
        super('group', layerTreeGroupCfg, parentMapGroup);
        // if checkboxes are hided for groups then they are checked by default
        if (hideGroupCheckbox) {
            this._checked = true;
        }
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +                const group = new LayerGroupState(layerTreeItem, layersOrder, options, this);
```suggestion
                const group = new LayerGroupState(layerTreeItem, layersOrder, hideGroupCheckbox, this);
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +                    layer = new LayerVectorState(layerTreeItem, layersOrder, options, this);
```suggestion
                    layer = new LayerVectorState(layerTreeItem, layersOrder, this);
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +                    layer = new LayerRasterState(layerTreeItem, layersOrder, options, this);
```suggestion
                    layer = new LayerRasterState(layerTreeItem, layersOrder, this);
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +     * @param {OptionsConfig}        options           - the option instance from lizMap configuration
```suggestion
     * @param {boolean}        hideGroupCheckbox           - the hideGroupCheckbox option instance from lizMap configuration
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +    constructor(layerTreeGroupCfg, layersOrder, options) {
```suggestion
    constructor(layerTreeGroupCfg, layersOrder, hideGroupCheckbox) {
```

2024-07-30 10:26 UTC, rldhont commented on assets/src/modules/state/Layer.js
> +        this._root = new LayerGroupState(layerTreeGroupCfg, layersOrder, options);
```suggestion
        this._root = new LayerGroupState(layerTreeGroupCfg, layersOrder, hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/baselayer.test.js
> +    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/baselayer.test.js
> +        const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
        const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/externallayertree.test.js
> +    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/externalmaplayer.test.js
> +    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
        const options = new OptionsConfig(config.options);
        const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/layer.test.js
> +    const root = new LayerGroupState(rootCfg, layersOrder, options);
```suggestion
    const root = new LayerGroupState(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/layer.test.js
> +    return new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
    return new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/layer.test.js
> +        const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
        const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/layerTree.test.js
> +    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 10:26 UTC, rldhont commented on tests/js-units/node/state/maplayer.test.js
> +    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options);
```suggestion
    const collection = new LayersAndGroupsCollection(rootCfg, layersOrder, options.hideGroupCheckbox);
```

2024-07-30 16:18 UTC, rldhont approved these changes

2024-07-30 16:21 UTC, rldhont commented
Thanks @mind84 before merging I have 2 questions 
* Is this PR fixes https://github.com/3liz/lizmap-web-client/issues/3968 and https://github.com/3liz/lizmap-web-client/issues/4232 ?
* Were you thinking of a backport? If yes for which version ?

2024-07-31 07:17 UTC, mind84 commented
Hi @rldhont,

thank you for taking time to review this PR

> Is this PR fixes https://github.com/3liz/lizmap-web-client/issues/3968 and https://github.com/3liz/lizmap-web-client/issues/4232 ?

Yes, I'll add this information to PR description

> Were you thinking of a backport? If yes for which version ?

Yes, I think this could be backported in 3.8 at least, if you don't see any blocker

Thanks!

2024-07-31 14:20 UTC, Gustry commented on assets/src/modules/state/Layer.js
> +        // prop checked is inherithed from Lizmap configuration. if checkboxes are hided for groups then they are checked by default
```suggestion
        // prop checked is inherited from Lizmap configuration. If checkboxes are hidden for groups then they are checked by default
```

2024-07-31 14:20 UTC, Gustry commented on assets/src/modules/state/Layer.js
> +        // if checkboxes are hided for groups then they are checked by default
```suggestion
        // if checkboxes are hidden for groups then they are checked by default
```
https://www.grammarflex.com/whats-the-past-tense-of-hide-is-it-hid-or-hidden/#Forms_of_the_verb_hide

2024-07-31 14:20 UTC, Gustry commented on tests/end2end/playwright/permalink.spec.js
> +        // legend_option_test is a group, it has no stile
```suggestion
        // legend_option_test is a group, it has no style
```

2024-07-31 14:20 UTC, Gustry commented on tests/end2end/playwright/permalink.spec.js
> +        // legend_option_test is a group, it has no stile
```suggestion
        // legend_option_test is a group, it has no style
```

2024-07-31 14:20 UTC, Gustry commented on tests/end2end/playwright/permalink.spec.js
> +        // legend_option_test is a group, it has no stile
Same

2024-07-31 14:20 UTC, Gustry commented on tests/end2end/playwright/permalink.spec.js
> +        // legend_option_test is a group, it has no stile
Same

2024-07-31 17:11 UTC, merged