Action: allow geometry drawn by user
3liz/lizmap-web-client pull request #4754
Opened 2024-09-16 14:19 UTC by nboisteault

Funded by WPD

2024-10-15 18:04 UTC, rldhont approved these changes

2024-10-15 18:04 UTC, rldhont commented
waiting for @mdouchin review!

2024-10-16 12:25 UTC, mdouchin requested changes
Thanks for your work.
Can you please improve the UI a bit :

* use the same space between the left mini-dock border and the digitizing toolbar (and message underneath) as the space used for the combobox and "grey" description. It seems. Be careful about testing it with a without Bootstrap 5
* we shoud probably remove the grey background color of the description and use a lighter style, for example a thin blue border as used in the editing form group 
```css
border: 1px solid var(--color-contrasted-elements-light);
border-radius: 5px;
``` 

Thanks !

2024-11-05 14:51 UTC, merged

2024-11-05 15:42 UTC, Gustry commented
Sorry @nboisteault I just tried this PR.

> we should probably remove the grey background color

I can only agree with this proposition, the current grey background is legacy and still present.

AS talked with @rldhont and @mdouchin, if the `geometry` is set for the action, so the geometry is **required**. We shouldn't be able to launch the action without a geometry.
I think the "Launch" button should be disabled until we do not have a geometry. Otherwise, we have the error message set the SQL function code :

![image](https://github.com/user-attachments/assets/75ac9e72-a2a8-40c8-a030-abcf8024a607)