Zoom to features with a max scale constraint
3liz/lizmap-web-client pull request #4897
Opened 2024-10-21 15:41 UTC by nboisteault

2024-12-03 17:36 UTC, rldhont requested changes
remove `lizMap` from `LocateByLayer` module.

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        if (mainLizmap.initialConfig.locateByLayer) {
```suggestion
    /**
     * Build the lizmap LocateByLayer instance
     * @param {LocateByLayerConfig} locateByLayer - The lizmap locateByLayer config
     * @param {WfsFeatureType[]} vectorLayerFeatureTypeList - The list of WFS feature type
     * @param {Map}           map           - OpenLayers map
     * @param {object}        lizmap3       - The old lizmap object
     */
    constructor(locateByLayer, vectorLayerFeatureTypeList, map, lizmap3) {
        this._map = map;
        this._vectorLayerFeatureTypeList = vectorLayerFeatureTypeList;
        
        this._lizmap3 = lizmap3;
        this._lizmap3LocateByLayerConfig = lizmap3.config.locateByLayer;
        
        const locateBtn = document.getElementById('button-locate');
        if (locateByLayer) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                locateByLayerList[this._locateByLayerConfig[lname].order] = lname;
```suggestion
        for (var lname in this._lizmap3LocateByLayerConfig) {
            if ('order' in this._lizmap3ocateByLayerConfig[lname])
                locateByLayerList[this._lizmap3ocateByLayerConfig[lname].order] = lname;
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            var lConfig = lizMap.config.layers[lname];
```suggestion
            var lConfig = this._lizmap3.config.layers[lname];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            html += '<select id="locate-layer-' + lizMap.cleanName(lname) + '" class="label">';
```suggestion
            html += '<select id="locate-layer-' + this._lizmap3.cleanName(lname) + '" class="label">';
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            this._locateByLayerConfig = {};
```suggestion
            this._lizmap3LocateByLayerConfig = {};
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                        for (var lbl in this._locateByLayerConfig) {
```suggestion
                    if (typeName in this._lizmap3LocateByLayerConfig)
                        lname = typeName
                    else if ((typeName in shortNameMap) && (shortNameMap[typeName] in this._lizmap3LocateByLayerConfig))
                        lname = shortNameMap[typeName];
                    else {
                        for (var lbl in this._lizmap3LocateByLayerConfig) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                var locate = this._locateByLayerConfig[lname];
```suggestion
                if (!(lname in this._lizmap3LocateByLayerConfig))
                    continue;

                var locate = this._lizmap3LocateByLayerConfig[lname];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                        var jLocate = this._locateByLayerConfig[jName];
```suggestion
            for (var lName in this._lizmap3LocateByLayerConfig) {
                var locate = this._lizmap3LocateByLayerConfig[lName];
                if ('vectorjoins' in locate && locate['vectorjoins'].length != 0) {
                    var vectorjoin = locate['vectorjoins'][0];
                    locate['joinFieldName'] = vectorjoin['targetFieldName'];
                    for (var jName in this._lizmap3LocateByLayerConfig) {
                        var jLocate = this._lizmap3LocateByLayerConfig[jName];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            for (var lname in this._locateByLayerConfig) {
```suggestion
            for (var lname in this._lizmap3LocateByLayerConfig) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                    lizMap.events.triggerEvent('lizmaplocatefeaturecanceled',
```suggestion
                if (this._lizmap3.lizmapLayerFilterActive) {
                    this._lizmap3.events.triggerEvent('lizmaplocatefeaturecanceled',
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        var locate = this._locateByLayerConfig[aName];
```suggestion
        var locate = this._lizmap3LocateByLayerConfig[aName];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        var getFeatureUrlData = lizMap.getVectorLayerWfsUrl( aName, null, null, 'extent' );
```suggestion
        var getFeatureUrlData = this._lizmap3.getVectorLayerWfsUrl( aName, null, null, 'extent' );
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        var layerName = lizMap.cleanName(aName);
```suggestion
        var layerName = this._lizmap3.cleanName(aName);
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            var lConfig = lizMap.config.layers[aName];
```suggestion
            var lConfig = this._lizmap3.config.layers[aName];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                            if ( jName in this._locateByLayerConfig ) {
```suggestion
                            if ( jName in this._lizmap3LocateByLayerConfig ) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                        if ( jName in this._locateByLayerConfig ) {
```suggestion
                        if ( jName in this._lizmap3LocateByLayerConfig ) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                            if ( jName in this._locateByLayerConfig ) {
```suggestion
                            if ( jName in this._lizmap3LocateByLayerConfig ) {
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            lizMap.events.triggerEvent('lizmaplocatefeaturecanceled', {'featureType': aName });
```suggestion
        var locate = this._lizmap3LocateByLayerConfig[aName];
        var layerName = this._lizmap3.cleanName(aName);
        var val = $('#locate-layer-'+layerName).val();
        if (val == '-1') {
            // Trigger event
            this._lizmap3.events.triggerEvent('lizmaplocatefeaturecanceled', {'featureType': aName });
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            lizMap.events.triggerEvent('lizmaplocatefeaturechanged',
```suggestion
            this._lizmap3.events.triggerEvent('lizmaplocatefeaturechanged',
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        var locate = this._locateByLayerConfig[aName];
```suggestion
        var locate = this._lizmap3LocateByLayerConfig[aName];
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +            var filterValue = $('#locate-layer-' + lizMap.cleanName(aName) + '-'+locate.filterFieldName).val();
```suggestion
            var filterValue = $('#locate-layer-' + this._lizmap3.cleanName(aName) + '-'+locate.filterFieldName).val();
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                    var jVal = $('#locate-layer-' + lizMap.cleanName(jName)).val();
```suggestion
                    var jLocate = this._lizmap3LocateByLayerConfig[jName];
                    var jVal = $('#locate-layer-' + this._lizmap3.cleanName(jName)).val();
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        $('#locate-layer-'+ lizMap.cleanName(aName)).html(options);
```suggestion
        $('#locate-layer-'+ this._lizmap3.cleanName(aName)).html(options);
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        const placeHolder = lizMap.config.layers[aName].title;
```suggestion
        const placeHolder = this._lizmap3.config.layers[aName].title;
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                lizMap.mainLizmap.map.clearHighlightFeatures();
```suggestion
                this._map.clearHighlightFeatures();
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        lizMap.mainLizmap.map.clearHighlightFeatures();
```suggestion
        this._map.clearHighlightFeatures();
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +                lizMap.mainLizmap.map.zoomToGeometryOrExtent(geom);
```suggestion
                        this._map.setHighlightFeatures(data.features[0], "geojson");
                    }).fail(function(){
                        this._map.setHighlightFeatures(feat, "geojson");
                    });
                }
                // zoom to extent
                this._map.zoomToGeometryOrExtent(geom);
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/LocateByLayer.js
> +        var featureTypes = lizMap.mainLizmap.initialConfig.vectorLayerFeatureTypeList;
```suggestion
        var featureTypes = this._vectorLayerFeatureTypeList;
```

2024-12-03 17:36 UTC, rldhont commented on assets/src/modules/Lizmap.js
> +                this.locateByLayer = new LocateByLayer();
```suggestion
                this.locateByLayer = new LocateByLayer(
                    this.initialConfig.locateByLayer,
                    this.initialConfig.vectorLayerFeatureTypeList,
                    this.map,
                    this._lizmap3
                );
```

2024-12-05 16:29 UTC, nboisteault commented
ok to merge?

2024-12-05 16:38 UTC, rldhont approved these changes

2024-12-05 16:38 UTC, merged

2024-12-05 16:38 UTC, rldhont commented
Thanks @nboisteault

2024-12-05 16:57 UTC, Gustry commented
Please provide a description in the PR ;-)